import { Jost } from 'next/font/google';
import './globals.css';
import StarRating from '@/components/StarRating';

const montserrat = Jost({
  subsets: ['latin'],
  weight: ['100', '400', '600', '800'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>{children}</body>
      {/* <body className={montserrat.className}>
        <StarRating maxRating={6} />
      </body> */}
    </html>
  );
}
